/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#680009",
        "surface-container-low": "#1c1b1b",
        "secondary-container": "#af8d11",
        "outline-variant": "#59413f",
        "surface-bright": "#3a3939",
        "surface-dim": "#131313",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001c39",
        "surface-container": "#201f1f",
        "on-tertiary": "#00315d",
        "secondary-fixed": "#ffe088",
        "secondary-fixed-dim": "#e9c349",
        "primary-container": "#8a0b14",
        "on-secondary-fixed-variant": "#574500",
        "tertiary": "#a4c9ff",
        "on-primary-fixed-variant": "#8f1017",
        "surface-container-high": "#2a2a2a",
        "primary-fixed": "#ffdad6",
        "on-tertiary-fixed-variant": "#084882",
        "background": "#131313",
        "on-surface": "#e5e2e1",
        "secondary": "#e9c349",
        "tertiary-fixed": "#d4e3ff",
        "on-primary-container": "#ff928a",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#410003",
        "error": "#ffb4ab",
        "outline": "#a88a87",
        "tertiary-container": "#00447e",
        "primary": "#ffb3ad",
        "surface": "#131313",
        "on-secondary-fixed": "#241a00",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-container": "#85b3f3",
        "inverse-on-surface": "#313030",
        "error-container": "#93000a",
        "surface-tint": "#ffb3ad",
        "tertiary-fixed-dim": "#a4c9ff",
        "on-secondary": "#3c2f00",
        "on-secondary-container": "#342800",
        "on-surface-variant": "#e1bfbb",
        "surface-container-highest": "#353534",
        "on-background": "#e5e2e1",
        "on-error": "#690005",
        "surface-variant": "#353534",
        "primary-fixed-dim": "#ffb3ad",
        "inverse-primary": "#b12c2b",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "4rem",
        "space-2xs": "0.25rem",
        "gutter-desktop": "2rem",
        "space-4xl": "6rem",
        "space-xs": "0.5rem",
        "space-3xl": "4.5rem",
        "space-md": "1rem",
        "margin-mobile": "1.25rem",
        "space-3xs": "0.125rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-2xl": "3rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem"
      },
      fontFamily: {
        "label-caps": ["'Geist'", "sans-serif"],
        "title-editorial": ["'Bodoni Moda'", "serif"],
        "body-lg": ["'Geist'", "sans-serif"],
        "display-hero": ["'Bodoni Moda'", "serif"],
        "body-md": ["'Geist'", "sans-serif"],
        "headline-md": ["'Bodoni Moda'", "serif"],
        "headline-lg": ["'Bodoni Moda'", "serif"],
        "body-sm": ["'Geist'", "sans-serif"],
        "display-hero-mobile": ["'Bodoni Moda'", "serif"],
        "headline-xl-mobile": ["'Bodoni Moda'", "serif"],
        "headline-xl": ["'Bodoni Moda'", "serif"],
        "label-data": ["'Geist'", "sans-serif"],
        "headline-lg-mobile": ["'Bodoni Moda'", "serif"],
        "headline-sm": ["'Bodoni Moda'", "serif"],
      },
      fontSize: {
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.22em", fontWeight: "600" }],
        "title-editorial": ["18px", { lineHeight: "26px", letterSpacing: "0.08em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0.01em", fontWeight: "400" }],
        "display-hero": ["96px", { lineHeight: "100px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0.015em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "500" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "400" }],
        "display-hero-mobile": ["48px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-xl": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-data": ["13px", { lineHeight: "18px", letterSpacing: "0.06em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-sm": ["22px", { lineHeight: "30px", letterSpacing: "0.01em", fontWeight: "500" }],
      }
    },
  },
  plugins: [],
}
